# Generated by Django 2.0.5 on 2018-06-20 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreUserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('college_name', models.CharField(max_length=100, verbose_name='College Name')),
                ('github_id', models.CharField(blank=True, max_length=50, verbose_name='Github Username')),
                ('hackerrank_id', models.CharField(blank=True, max_length=50, verbose_name='Hackerrank Username')),
                ('codechef_id', models.CharField(blank=True, max_length=50, verbose_name='Codechef Username')),
                ('codeforces_id', models.CharField(blank=True, max_length=50, verbose_name='Codeforces Username')),
            ],
        ),
    ]
