# Generated by Django 2.0.5 on 2018-06-20 15:33

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreuserdata',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Please upload a Profile Picture', upload_to=data.models.get_profilepic_upload_url, verbose_name='Profile Picture'),
        ),
    ]
