# Generated by Django 2.0.5 on 2018-06-22 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_moreuserdata_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreuserdata',
            name='secret_key',
            field=models.CharField(default=123456789123456, max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Secret Key'),
            preserve_default=False,
        ),
    ]
