# Generated by Django 2.0.5 on 2018-06-22 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_moreuserdata_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreuserdata',
            name='secret_key',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Secret Key'),
        ),
    ]
