# Generated by Django 2.0.6 on 2018-06-26 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180622_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreuserdata',
            name='secret_key',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.MinLengthValidator(32)], verbose_name='Secret Key'),
        ),
    ]
