# Generated by Django 2.0.5 on 2018-06-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(verbose_name='Event Concludes On (IST)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organisers',
            field=models.ManyToManyField(help_text='Please Select 1 or more users as Organisers', related_name='organising_events', to='data.MoreUserData'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_events', to='data.MoreUserData'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(verbose_name='Event Starts On (IST) '),
        ),
    ]
