# Generated by Django 2.0.5 on 2018-06-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180622_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreuserdata',
            name='description',
            field=models.TextField(blank=True, help_text='Write A Few Lines About Yourself', verbose_name='About You'),
        ),
    ]
