# Generated by Django 2.0.5 on 2018-06-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180622_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.IntegerField(default=0, help_text='Events will be listed Based on priority. Higher Priority events appear first in list', verbose_name='Priority'),
        ),
    ]
