# Generated by Django 2.0.5 on 2018-06-23 15:48

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180623_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_logo',
            field=models.ImageField(blank=True, help_text='Please Upload A Logo For This Event', upload_to=data.models.get_event_logo_upload_url, verbose_name='Event Logo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(default=0, help_text='Events will be ordered Based on priority. Higher Priority events appear first in list', verbose_name='Priority'),
        ),
    ]
