# Generated by Django 2.0.5 on 2018-06-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20180623_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_logo',
            new_name='logo',
        ),
    ]
