# Generated by Django 2.0.5 on 2018-06-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180626_1306'),
        ('data', '0011_auto_20180624_0034'),
    ]

    operations = [
    ]
