# Generated by Django 2.0.5 on 2018-06-26 15:00

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_merge_20180626_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCatalogue',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.Event')),
                ('image1', models.ImageField(blank=True, help_text='Upload Image 1 for this Event. (optional). This is primary image that will appear on main page', upload_to=data.models.get_event_catalogue_upload_url, verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, help_text='Upload Image 1 for this Event. (optional)', upload_to=data.models.get_event_catalogue_upload_url, verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, help_text='Upload Image 1 for this Event. (optional)', upload_to=data.models.get_event_catalogue_upload_url, verbose_name='Image 3')),
                ('image4', models.ImageField(blank=True, help_text='Upload Image 1 for this Event. (optional)', upload_to=data.models.get_event_catalogue_upload_url, verbose_name='Image 4')),
                ('image5', models.ImageField(blank=True, help_text='Upload Image 1 for this Event. (optional)', upload_to=data.models.get_event_catalogue_upload_url, verbose_name='Image 5')),
                ('image6', models.ImageField(blank=True, help_text='Upload Image 1 for this Event. (optional)', upload_to=data.models.get_event_catalogue_upload_url, verbose_name='Image 6')),
            ],
        ),
    ]
