# Generated by Django 2.0.5 on 2018-06-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20180626_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcatalogue',
            options={'ordering': ['event']},
        ),
    ]
