# Generated by Django 2.0.5 on 2018-06-28 14:44

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_merge_20180628_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text="All characters allowed except '-' as this may collide with slug of event name", max_length=50, unique=True, validators=[data.models.event_name_slug_validator], verbose_name='Event Name'),
        ),
    ]
