# Generated by Django 2.0.5 on 2018-06-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_merge_20180628_1418'),
        ('data', '0018_emailconfirmation'),
    ]

    operations = [
    ]
