# Generated by Django 2.0.5 on 2018-07-02 16:01

import data.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_merge_20180701_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('committee_lgo', models.ImageField(blank=True, upload_to=data.models.get_committee_upload_url, verbose_name='Committee Logo')),
                ('members', models.ManyToManyField(blank=True, to='data.MoreUserData')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Enter The contact number of committee without the preceeding country code', max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.Committee')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='organisers',
            field=models.ManyToManyField(blank=True, help_text='Please Select 1 or more users as Organisers', related_name='organising_events', to='data.MoreUserData'),
        ),
    ]
