# Generated by Django 2.0.5 on 2018-07-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20180702_2131'),
        ('data', '0019_merge_20180701_0020'),
    ]

    operations = [
    ]
