# Generated by Django 2.0.5 on 2018-07-07 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_merge_20180707_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreuserdata',
            name='country_code',
            field=models.CharField(choices=[('+91', 'India(+91)'), ('+7', 'Russia(+7)'), ('+81', 'Japan(+81)'), ('+1', 'USA(+1)'), ('+972', 'Israel(+972)')], default='+91', max_length=4, verbose_name='Country Code for Phone Number'),
        ),
        migrations.AddField(
            model_name='moreuserdata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='moreuserdata',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('S', 'Small(S)'), ('M', 'Medium(M)'), ('L', 'Large(L)'), ('XL', 'Extra Large(XL)'), ('XXL', 'Extra Extra Large(XXL)')], help_text='Enter your T shirt size so that we can get you one if you win', max_length=3, verbose_name='T-Shirt Size'),
        ),
    ]
