# Generated by Django 2.0.5 on 2018-07-17 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_auto_20180717_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 13, 42, 21, 674052, tzinfo=utc), verbose_name='Registration Ends On (IST) '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 13, 42, 39, 878230, tzinfo=utc), verbose_name='Registration Starts On (IST) '),
            preserve_default=False,
        ),
    ]
