# Generated by Django 2.0.5 on 2018-07-25 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0026_auto_20180717_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=35)),
                ('content', models.CharField(max_length=500)),
                ('button1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dynamic link for URLs')),
                ('button1_url', models.URLField()),
                ('button2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dynamic link for URLS')),
                ('button2_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
