# Generated by Django 2.0.5 on 2018-07-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='button1_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='button2_url',
            field=models.URLField(blank=True),
        ),
    ]
