# Generated by Django 2.0.5 on 2018-07-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_auto_20180725_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='keyword',
            field=models.CharField(blank=True, help_text='Keyword that identifies different types of updates', max_length=15, null=True),
        ),
    ]
