# Generated by Django 2.0.5 on 2018-08-12 06:32

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_notification_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreuserdata',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Please upload a Profile Picture', null=True, upload_to=data.models.get_profilepic_upload_url, verbose_name='Profile Picture'),
        ),
    ]
