# Generated by Django 2.0.5 on 2018-07-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_notification_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Catagory Name')),
                ('events', models.ManyToManyField(blank=True, to='data.Event', verbose_name='Events belonging to this catagory')),
            ],
        ),
    ]
