# Generated by Django 2.0.5 on 2018-07-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_eventcatagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcatagory',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='catagories', to='data.Event', verbose_name='Events belonging to this catagory'),
        ),
    ]
